/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityfund.ui;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.persistence.EntityManager;
import universityfund.db.DbHelper;
import universityfund.db.models.Donor;
import universityfund.db.models.Funding;
import universityfund.db.models.Pledges;

/**
 *
 * @author MiriamMarie
 */
public class AddPledgeWindow extends javax.swing.JFrame implements UI{
    Donor selectedDonor;
    /**
     * Creates new form PledgeWindow
     */
    public AddPledgeWindow() {
        initComponents();
        selectedDonor = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentGroup = new javax.swing.ButtonGroup();
        methodGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        name_text = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        amount_label = new javax.swing.JLabel();
        amount_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        corpName_text = new javax.swing.JTextField();
        corpAdd_panel = new javax.swing.JScrollPane();
        corpAdd_text = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        spouse_text = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        payment_label = new javax.swing.JLabel();
        deffered_rButton = new javax.swing.JRadioButton();
        card_rButton = new javax.swing.JRadioButton();
        cash_rButton = new javax.swing.JRadioButton();
        single_rButton = new javax.swing.JRadioButton();
        method_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        number_spinner = new javax.swing.JSpinner();
        cc_label = new javax.swing.JLabel();
        cc_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW PLEDGE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pledge Information");

        name_label.setText("Name:");

        name_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_text.setText(" ");
        name_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        select_button.setText("Set...");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });

        amount_label.setText("Amount:");

        amount_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_textActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matching Gift");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setText("Corporation Name:");

        jLabel6.setText("Corporation Address:");

        corpName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                corpName_textKeyTyped(evt);
            }
        });

        corpAdd_text.setColumns(20);
        corpAdd_text.setLineWrap(true);
        corpAdd_text.setRows(5);
        corpAdd_text.setWrapStyleWord(true);
        corpAdd_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                corpAdd_textKeyTyped(evt);
            }
        });
        corpAdd_panel.setViewportView(corpAdd_text);

        jLabel7.setText("Name of Spouse:");

        spouse_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spouse_textKeyTyped(evt);
            }
        });

        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        payment_label.setText("Kind of Payment:");

        deffered_rButton.setBackground(new java.awt.Color(255, 255, 255));
        paymentGroup.add(deffered_rButton);
        deffered_rButton.setText("Deffered Payment");
        deffered_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deffered_rButtonActionPerformed(evt);
            }
        });

        card_rButton.setBackground(new java.awt.Color(255, 255, 255));
        methodGroup.add(card_rButton);
        card_rButton.setText("Credit Card");
        card_rButton.setEnabled(false);
        card_rButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                card_rButtonItemStateChanged(evt);
            }
        });

        cash_rButton.setBackground(new java.awt.Color(255, 255, 255));
        methodGroup.add(cash_rButton);
        cash_rButton.setText("Cash");
        cash_rButton.setEnabled(false);
        cash_rButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cash_rButtonItemStateChanged(evt);
            }
        });

        single_rButton.setBackground(new java.awt.Color(255, 255, 255));
        paymentGroup.add(single_rButton);
        single_rButton.setText("Single Payment");
        single_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                single_rButtonActionPerformed(evt);
            }
        });

        method_label.setText("Method");

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabel8.setText("Number of Payments:");

        number_spinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 12, 1));
        number_spinner.setEnabled(false);

        cc_label.setText("CC#:");

        cc_text.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_button)
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corpName_text))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corpAdd_panel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spouse_text))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(amount_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amount_text))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(name_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(select_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(deffered_rButton)
                                        .addGap(10, 10, 10)
                                        .addComponent(single_rButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(payment_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(method_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cash_rButton)
                                        .addGap(10, 10, 10)
                                        .addComponent(card_rButton))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cc_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cc_text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name_label)
                        .addComponent(select_button)
                        .addComponent(jLabel3))
                    .addComponent(name_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_label)
                    .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_label)
                    .addComponent(method_label)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deffered_rButton)
                    .addComponent(card_rButton)
                    .addComponent(cash_rButton)
                    .addComponent(single_rButton))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cc_label)
                    .addComponent(cc_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(corpName_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(corpAdd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spouse_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        new SelectDonorWindow(this).setVisible(true);
    }//GEN-LAST:event_select_buttonActionPerformed

    private void amount_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_textActionPerformed

    private void deffered_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deffered_rButtonActionPerformed
        if(deffered_rButton.isSelected()){
            cash_rButton.setEnabled(true);
            card_rButton.setEnabled(true);
            number_spinner.setEnabled(true);
        } else {
            cash_rButton.setEnabled(false);
            card_rButton.setEnabled(false);
        }
    }//GEN-LAST:event_deffered_rButtonActionPerformed

    private void single_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_single_rButtonActionPerformed
        // TODO add your handling code here:
        if(single_rButton.isSelected()){
            cash_rButton.setEnabled(true);
            card_rButton.setEnabled(true);
            number_spinner.setEnabled(false);
        } else {
            cash_rButton.setEnabled(false);
            card_rButton.setEnabled(false);
        }
    }//GEN-LAST:event_single_rButtonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        if (!valid()) 
            return;
        createPledge();
        dispose();
    }//GEN-LAST:event_save_buttonActionPerformed

    private void card_rButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_card_rButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cc_text.setEnabled(true);
        } else {
            cc_text.setEnabled(false);
        }
    }//GEN-LAST:event_card_rButtonItemStateChanged

    private void spouse_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouse_textKeyTyped
        if (spouse_text.getText().trim().length() == 0) {
            corpName_text.setEnabled(true);
            corpAdd_text.setEnabled(true);
        } else {
            corpName_text.setEnabled(false);
            corpAdd_text.setEnabled(false);
        }
    }//GEN-LAST:event_spouse_textKeyTyped

    private void corpName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corpName_textKeyTyped
        spouse_text.setEnabled(
                corpName_text.getText().trim().length() == 0
                        && corpAdd_text.getText().trim().length() == 0
        );
    }//GEN-LAST:event_corpName_textKeyTyped

    private void corpAdd_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corpAdd_textKeyTyped
        spouse_text.setEnabled(
                corpAdd_text.getText().trim().length() == 0
                        && corpName_text.getText().trim().length() == 0
        );
    }//GEN-LAST:event_corpAdd_textKeyTyped

    private void cash_rButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cash_rButtonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            cc_text.setEnabled(false);
        } else {
            cc_text.setEnabled(true);
        }
    }//GEN-LAST:event_cash_rButtonItemStateChanged
    
    private void createPledge() {
        Pledges pledge = new Pledges();
        pledge.setDonor(selectedDonor);
        Funding funding;
        if (deffered_rButton.isSelected())
            funding = Funding.createFunding(
                    Integer.valueOf(amount_text.getText()),
                    (int) number_spinner.getValue()
            );
        else
            funding = Funding.createFunding(
                    Integer.valueOf(amount_text.getText())
            );
        pledge.setFunding(funding);
        if (corpName_text.isEnabled() && corpName_text.getText().trim().length() != 0) {
            pledge.setCorporationAddress(corpAdd_text.getText());
            pledge.setCorporationName(corpName_text.getText());
        } else {
            pledge.setNameOfSpouse(spouse_text.getText());
        }
        pledge.save();
    }
    
    private boolean valid() {
        boolean valid = true;
        if (selectedDonor == null) {
            name_label.setForeground(Color.RED);
            valid = false;
        } else {
            name_label.setForeground(Color.BLACK);
        }
        if (!amount_text.getText().matches("^[0-9]+$")) {
            amount_label.setForeground(Color.RED);
            valid = false;
        } else {
            amount_label.setForeground(Color.BLACK);
        }
        if (!(deffered_rButton.isSelected()||single_rButton.isSelected())) {
            payment_label.setForeground(Color.RED);
            valid = false;
        } else {
            payment_label.setForeground(Color.BLACK);
        }
        if (!(cash_rButton.isSelected()||card_rButton.isSelected())) {
            method_label.setForeground(Color.RED);
            valid = false;
        } else {
            method_label.setForeground(Color.BLACK);
        }
        if (card_rButton.isSelected()) {
            if ("".equals(cc_text.getText().trim()) || !cc_text.getText().matches("^[0-9]+$")) {
                cc_label.setForeground(Color.RED);
                valid = false;
            } else {
                cc_label.setForeground(Color.BLACK);
            }
        }
        return valid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_label;
    private javax.swing.JTextField amount_text;
    private javax.swing.JRadioButton card_rButton;
    private javax.swing.JRadioButton cash_rButton;
    private javax.swing.JLabel cc_label;
    private javax.swing.JTextField cc_text;
    private javax.swing.JScrollPane corpAdd_panel;
    private javax.swing.JTextArea corpAdd_text;
    private javax.swing.JTextField corpName_text;
    private javax.swing.JRadioButton deffered_rButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup methodGroup;
    private javax.swing.JLabel method_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel name_text;
    private javax.swing.JSpinner number_spinner;
    private javax.swing.ButtonGroup paymentGroup;
    private javax.swing.JLabel payment_label;
    private javax.swing.JButton save_button;
    private javax.swing.JButton select_button;
    private javax.swing.JRadioButton single_rButton;
    private javax.swing.JTextField spouse_text;
    // End of variables declaration//GEN-END:variables

    @Override
    public void receiveIntent(Object intent) {
        EntityManager em = DbHelper.getEntityManager();
        selectedDonor = em.find(Donor.class, (long) intent);
        name_text.setText(selectedDonor.getName());
    }
}
