/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityfund.ui;

import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import universityfund.db.DbHelper;
import universityfund.db.models.Donor;
import universityfund.db.models.Funding;
import universityfund.db.models.FundingId;
import universityfund.db.models.Pledges;

/**
 *
 * @author MiriamMarie
 */
public class ModifyPledgeWindow extends javax.swing.JFrame implements UI {
    Pledges selectedPledge;
    /**
     * Creates new form ModifyPledgeWindow
     */
    public ModifyPledgeWindow() {
        initComponents();
        selectedPledge = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payment_group = new javax.swing.ButtonGroup();
        method_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        id_text = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        amount_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        corpName_text = new javax.swing.JTextField();
        corpAdd_panel = new javax.swing.JScrollPane();
        corpAdd_text = new javax.swing.JTextArea();
        spouse_text = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        deferred_rButton = new javax.swing.JRadioButton();
        card_rButton = new javax.swing.JRadioButton();
        cash_rButton = new javax.swing.JRadioButton();
        single_rButton = new javax.swing.JRadioButton();
        number_spinner = new javax.swing.JSpinner();
        cc_text = new javax.swing.JTextField();
        amount_box = new javax.swing.JCheckBox();
        payment_box = new javax.swing.JCheckBox();
        method_box = new javax.swing.JCheckBox();
        number_box = new javax.swing.JCheckBox();
        cc_box = new javax.swing.JCheckBox();
        corpName_box = new javax.swing.JCheckBox();
        corpAdd_box = new javax.swing.JCheckBox();
        spouse_box = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE PLEDGE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify Pledge");

        id_label.setText("Pledge ID:");

        id_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        select_button.setText("Set...");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });

        amount_text.setEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Matching Gift");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        corpName_text.setEnabled(false);

        corpAdd_text.setColumns(20);
        corpAdd_text.setLineWrap(true);
        corpAdd_text.setRows(5);
        corpAdd_text.setWrapStyleWord(true);
        corpAdd_text.setEnabled(false);
        corpAdd_panel.setViewportView(corpAdd_text);

        spouse_text.setEnabled(false);

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        deferred_rButton.setBackground(new java.awt.Color(255, 255, 255));
        payment_group.add(deferred_rButton);
        deferred_rButton.setText("Deferred Payment");
        deferred_rButton.setEnabled(false);
        deferred_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deferred_rButtonActionPerformed(evt);
            }
        });

        card_rButton.setBackground(new java.awt.Color(255, 255, 255));
        method_group.add(card_rButton);
        card_rButton.setText("Credit Card");
        card_rButton.setEnabled(false);
        card_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card_rButtonActionPerformed(evt);
            }
        });

        cash_rButton.setBackground(new java.awt.Color(255, 255, 255));
        method_group.add(cash_rButton);
        cash_rButton.setText("Cash");
        cash_rButton.setEnabled(false);
        cash_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_rButtonActionPerformed(evt);
            }
        });

        single_rButton.setBackground(new java.awt.Color(255, 255, 255));
        payment_group.add(single_rButton);
        single_rButton.setText("Single Payment");
        single_rButton.setEnabled(false);
        single_rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                single_rButtonActionPerformed(evt);
            }
        });

        number_spinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 12, 1));
        number_spinner.setEnabled(false);

        cc_text.setEnabled(false);

        amount_box.setBackground(new java.awt.Color(255, 255, 255));
        amount_box.setText("Amount:");
        amount_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_boxActionPerformed(evt);
            }
        });

        payment_box.setBackground(new java.awt.Color(255, 255, 255));
        payment_box.setText("Mode of Payment:");
        payment_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_boxActionPerformed(evt);
            }
        });

        method_box.setBackground(new java.awt.Color(255, 255, 255));
        method_box.setText("Method:");
        method_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                method_boxActionPerformed(evt);
            }
        });

        number_box.setBackground(new java.awt.Color(255, 255, 255));
        number_box.setText("No. of Payments:");
        number_box.setEnabled(false);
        number_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_boxActionPerformed(evt);
            }
        });

        cc_box.setBackground(new java.awt.Color(255, 255, 255));
        cc_box.setText("CC#:");
        cc_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc_boxActionPerformed(evt);
            }
        });

        corpName_box.setBackground(new java.awt.Color(255, 255, 255));
        corpName_box.setText("Corporation Name:");
        corpName_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corpName_boxActionPerformed(evt);
            }
        });

        corpAdd_box.setBackground(new java.awt.Color(255, 255, 255));
        corpAdd_box.setText("Corporation Address:");
        corpAdd_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corpAdd_boxActionPerformed(evt);
            }
        });

        spouse_box.setBackground(new java.awt.Color(255, 255, 255));
        spouse_box.setText("Name of Spouse:");
        spouse_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouse_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payment_box)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deferred_rButton)
                                    .addComponent(number_box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(single_rButton)
                                    .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(method_box)
                                .addGap(67, 67, 67)
                                .addComponent(card_rButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(cash_rButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cc_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cc_text))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(amount_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amount_text))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(select_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(spouse_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spouse_text))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(corpAdd_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(corpAdd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(corpName_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(corpName_text))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(update_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_label)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(select_button)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payment_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deferred_rButton)
                    .addComponent(single_rButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_box)
                    .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(method_box)
                    .addComponent(cash_rButton)
                    .addComponent(card_rButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc_box)
                    .addComponent(cc_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corpName_box)
                    .addComponent(corpName_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corpAdd_box)
                    .addComponent(corpAdd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spouse_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouse_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        new SelectPledgeWindow(this).setVisible(true);
    }//GEN-LAST:event_select_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        if(valid()){
            updatePledge();
            new SuccessWindow().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    public void updatePledge(){
        Pledges pledge = selectedPledge;
        Funding funding = selectedPledge.getFunding();
        if(amount_box.isSelected())
            funding.setAmount(Integer.valueOf(amount_text.getText()));
        if(payment_box.isSelected()){
            if(deferred_rButton.isSelected())
                funding.setNumberOfPayments(2);
            else if(single_rButton.isSelected())
                funding.setNumberOfPayments(1);                
        }
        if(number_box.isSelected()){
            funding.setNumberOfPayments((int)number_spinner.getValue());
        }
        if(method_box.isSelected()){
            if(cash_rButton.isSelected())
                funding.setCreditCardNumber(null);
            if(card_rButton.isSelected())
                funding.setCreditCardNumber(cc_text.getText());
        }
        if(cc_box.isSelected())
            funding.setCreditCardNumber(cc_text.getText());
        Donor matching = pledge.getMatchingDonor();
        
        if(corpName_box.isSelected()) {
            if (matching == null && corpAdd_box.isSelected()) {
                matching = new Donor();
                matching.setAddress(corpAdd_text.getText());
                matching.setCategory("Corporation");
                matching.setName(corpName_text.getText());
                matching.save();
                pledge.setMatchingDonor(matching);
            } else if (matching != null) {
                matching.setName(corpName_text.getText());
            }
        }
        if(corpAdd_box.isSelected()) {
            if (matching == null && corpName_box.isSelected()) {
                matching = new Donor();
                matching.setAddress(corpAdd_text.getText());
                matching.setCategory("Corporation");
                matching.setName(corpName_text.getText());
                matching.save();
                pledge.setMatchingDonor(matching);
            } else if (matching != null) {
                matching.setAddress(corpAdd_text.getText());
                matching.save();
                pledge.setMatchingDonor(matching);
            }
            
        }
        if(spouse_box.isSelected() && !corpAdd_box.isSelected() && !corpName_box.isSelected()) {
            if (matching == null) {
                matching = new Donor();
                matching.setCategory("Spouse");
            }
            matching.setName(spouse_box.getText());
            matching.save();
            pledge.setMatchingDonor(matching);
        }
        pledge.save();
        funding.save();
    }
    
    private void amount_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_boxActionPerformed
        // TODO add your handling code here:
        if(amount_box.isSelected())
            amount_text.setEnabled(true);
        else amount_text.setEnabled(false);
    }//GEN-LAST:event_amount_boxActionPerformed

    private void payment_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_boxActionPerformed
        if(payment_box.isSelected()){
            deferred_rButton.setEnabled(true);
            single_rButton.setEnabled(true);
        } else {
            deferred_rButton.setEnabled(false);
            single_rButton.setEnabled(false);
        }
    }//GEN-LAST:event_payment_boxActionPerformed

    private void number_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_boxActionPerformed
        // TODO add your handling code here:
        if(number_box.isSelected())
            number_spinner.setEnabled(true);
        else number_spinner.setEnabled(false);
    }//GEN-LAST:event_number_boxActionPerformed

    private void method_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_method_boxActionPerformed
        // TODO add your handling code here:
        if(method_box.isSelected()){
            cash_rButton.setEnabled(true);
            card_rButton.setEnabled(true);
        } else {
            cash_rButton.setEnabled(false);
            card_rButton.setEnabled(false);
        }
    }//GEN-LAST:event_method_boxActionPerformed

    private void cc_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_boxActionPerformed
        if(cc_box.isSelected())
            cc_text.setEnabled(true);
        else cc_text.setEnabled(false);
    }//GEN-LAST:event_cc_boxActionPerformed

    private void corpName_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corpName_boxActionPerformed
        if(corpName_box.isSelected())
            corpName_text.setEnabled(true);
        else corpName_text.setEnabled(false);
    }//GEN-LAST:event_corpName_boxActionPerformed

    private void corpAdd_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corpAdd_boxActionPerformed
        if(corpAdd_box.isSelected())
            corpAdd_text.setEnabled(true);
        else corpAdd_text.setEnabled(false);
    }//GEN-LAST:event_corpAdd_boxActionPerformed

    private void spouse_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouse_boxActionPerformed
        if(spouse_box.isSelected())
            spouse_text.setEnabled(true);
        else spouse_text.setEnabled(false);
    }//GEN-LAST:event_spouse_boxActionPerformed

    private void single_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_single_rButtonActionPerformed
        number_box.setEnabled(false);
    }//GEN-LAST:event_single_rButtonActionPerformed

    private void deferred_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deferred_rButtonActionPerformed
        number_box.setEnabled(true);
    }//GEN-LAST:event_deferred_rButtonActionPerformed

    private void cash_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_rButtonActionPerformed
        cc_box.setEnabled(false);
    }//GEN-LAST:event_cash_rButtonActionPerformed

    private void card_rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card_rButtonActionPerformed
        cc_box.setEnabled(true);
    }//GEN-LAST:event_card_rButtonActionPerformed

    public boolean valid(){
        boolean valid = true;
        if(id_text.getText().isEmpty()){
            id_label.setForeground(Color.RED);
            valid = false;
        } else id_label.setForeground(Color.RED);
        return valid;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox amount_box;
    private javax.swing.JTextField amount_text;
    private javax.swing.JRadioButton card_rButton;
    private javax.swing.JRadioButton cash_rButton;
    private javax.swing.JCheckBox cc_box;
    private javax.swing.JTextField cc_text;
    private javax.swing.JCheckBox corpAdd_box;
    private javax.swing.JScrollPane corpAdd_panel;
    private javax.swing.JTextArea corpAdd_text;
    private javax.swing.JCheckBox corpName_box;
    private javax.swing.JTextField corpName_text;
    private javax.swing.JRadioButton deferred_rButton;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel id_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox method_box;
    private javax.swing.ButtonGroup method_group;
    private javax.swing.JCheckBox number_box;
    private javax.swing.JSpinner number_spinner;
    private javax.swing.JCheckBox payment_box;
    private javax.swing.ButtonGroup payment_group;
    private javax.swing.JButton select_button;
    private javax.swing.JRadioButton single_rButton;
    private javax.swing.JCheckBox spouse_box;
    private javax.swing.JTextField spouse_text;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void receiveIntent(Object intent) {
        EntityManager em = DbHelper.getEntityManager();
        long [] ids = (long[]) intent;
        selectedPledge = em.find(Pledges.class, new FundingId(ids[0], ids[1]));
        id_text.setText(String.valueOf(selectedPledge.getFunding().getId()));
    }
}
