/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityfund.ui;

import java.awt.Color;
import javax.persistence.EntityManager;
import universityfund.db.DbHelper;
import universityfund.db.models.FundingId;
import universityfund.db.models.Pledges;

/**
 *
 * @author MiriamMarie
 */
public class ModifyPledgeWindow extends javax.swing.JFrame implements UI {
    Pledges selectedPledge;
    /**
     * Creates new form ModifyPledgeWindow
     */
    public ModifyPledgeWindow() {
        initComponents();
        selectedPledge = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        id_text = new javax.swing.JLabel();
        select_button = new javax.swing.JButton();
        amount_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        corpName_text = new javax.swing.JTextField();
        corpAdd_panel = new javax.swing.JScrollPane();
        corpAdd_text = new javax.swing.JTextArea();
        spouse_text = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        deffered_rButton = new javax.swing.JRadioButton();
        card_rButton = new javax.swing.JRadioButton();
        cash_rButton = new javax.swing.JRadioButton();
        single_rButton = new javax.swing.JRadioButton();
        number_spinner = new javax.swing.JSpinner();
        cc_text = new javax.swing.JTextField();
        amount_box = new javax.swing.JCheckBox();
        payment_box = new javax.swing.JCheckBox();
        method_box = new javax.swing.JCheckBox();
        number_box = new javax.swing.JCheckBox();
        cc_box = new javax.swing.JCheckBox();
        corpName_box = new javax.swing.JCheckBox();
        corpAdd_box = new javax.swing.JCheckBox();
        spouse_box = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify Pledge");

        id_label.setText("Pledge ID:");

        id_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        select_button.setText("Set...");
        select_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_buttonActionPerformed(evt);
            }
        });

        amount_text.setEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Matching Gift");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        corpName_text.setEnabled(false);
        corpName_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                corpName_textKeyTyped(evt);
            }
        });

        corpAdd_text.setColumns(20);
        corpAdd_text.setLineWrap(true);
        corpAdd_text.setRows(5);
        corpAdd_text.setWrapStyleWord(true);
        corpAdd_text.setEnabled(false);
        corpAdd_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                corpAdd_textKeyTyped(evt);
            }
        });
        corpAdd_panel.setViewportView(corpAdd_text);

        spouse_text.setEnabled(false);
        spouse_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spouse_textKeyTyped(evt);
            }
        });

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        deffered_rButton.setBackground(new java.awt.Color(255, 255, 255));
        deffered_rButton.setText("Deffered Payment");
        deffered_rButton.setEnabled(false);

        card_rButton.setBackground(new java.awt.Color(255, 255, 255));
        card_rButton.setText("Credit Card");
        card_rButton.setEnabled(false);
        card_rButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                card_rButtonItemStateChanged(evt);
            }
        });

        cash_rButton.setBackground(new java.awt.Color(255, 255, 255));
        cash_rButton.setText("Cash");
        cash_rButton.setEnabled(false);
        cash_rButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cash_rButtonItemStateChanged(evt);
            }
        });

        single_rButton.setBackground(new java.awt.Color(255, 255, 255));
        single_rButton.setText("Single Payment");
        single_rButton.setEnabled(false);

        number_spinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 12, 1));
        number_spinner.setEnabled(false);

        cc_text.setEnabled(false);

        amount_box.setBackground(new java.awt.Color(255, 255, 255));
        amount_box.setText("Amount:");

        payment_box.setBackground(new java.awt.Color(255, 255, 255));
        payment_box.setText("Kind of Payment:");

        method_box.setBackground(new java.awt.Color(255, 255, 255));
        method_box.setText("Method:");

        number_box.setBackground(new java.awt.Color(255, 255, 255));
        number_box.setText("No. of Payments:");

        cc_box.setBackground(new java.awt.Color(255, 255, 255));
        cc_box.setText("CC#:");

        corpName_box.setBackground(new java.awt.Color(255, 255, 255));
        corpName_box.setText("Corporation Name:");

        corpAdd_box.setBackground(new java.awt.Color(255, 255, 255));
        corpAdd_box.setText("Corporation Address:");

        spouse_box.setBackground(new java.awt.Color(255, 255, 255));
        spouse_box.setText("Name of Spouse:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payment_box)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deffered_rButton)
                                    .addComponent(number_box))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(single_rButton)
                                    .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(method_box)
                                .addGap(67, 67, 67)
                                .addComponent(card_rButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(cash_rButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cc_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cc_text))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(amount_box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amount_text))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(select_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(spouse_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spouse_text))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(corpAdd_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(corpAdd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(corpName_box)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(corpName_text))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(update_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_label)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(select_button)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payment_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deffered_rButton)
                    .addComponent(single_rButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_box)
                    .addComponent(number_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(method_box)
                    .addComponent(cash_rButton)
                    .addComponent(card_rButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc_box)
                    .addComponent(cc_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corpName_box)
                    .addComponent(corpName_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corpAdd_box)
                    .addComponent(corpAdd_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spouse_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spouse_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_buttonActionPerformed
        new SelectPledgeWindow(this).setVisible(true);
    }//GEN-LAST:event_select_buttonActionPerformed

    private void corpName_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corpName_textKeyTyped

    }//GEN-LAST:event_corpName_textKeyTyped

    private void corpAdd_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corpAdd_textKeyTyped

    }//GEN-LAST:event_corpAdd_textKeyTyped

    private void spouse_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouse_textKeyTyped

    }//GEN-LAST:event_spouse_textKeyTyped

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed

    }//GEN-LAST:event_update_buttonActionPerformed

    private void card_rButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_card_rButtonItemStateChanged

    }//GEN-LAST:event_card_rButtonItemStateChanged

    private void cash_rButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cash_rButtonItemStateChanged

    }//GEN-LAST:event_cash_rButtonItemStateChanged

    public boolean valid(){
        boolean valid = true;
        if(id_text.getText().isEmpty()){
            id_label.setForeground(Color.RED);
            valid = false;
        } else id_label.setForeground(Color.RED);
        return valid;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox amount_box;
    private javax.swing.JTextField amount_text;
    private javax.swing.JRadioButton card_rButton;
    private javax.swing.JRadioButton cash_rButton;
    private javax.swing.JCheckBox cc_box;
    private javax.swing.JTextField cc_text;
    private javax.swing.JCheckBox corpAdd_box;
    private javax.swing.JScrollPane corpAdd_panel;
    private javax.swing.JTextArea corpAdd_text;
    private javax.swing.JCheckBox corpName_box;
    private javax.swing.JTextField corpName_text;
    private javax.swing.JRadioButton deffered_rButton;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel id_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox method_box;
    private javax.swing.JCheckBox number_box;
    private javax.swing.JSpinner number_spinner;
    private javax.swing.JCheckBox payment_box;
    private javax.swing.JButton select_button;
    private javax.swing.JRadioButton single_rButton;
    private javax.swing.JCheckBox spouse_box;
    private javax.swing.JTextField spouse_text;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void receiveIntent(Object intent) {
        EntityManager em = DbHelper.getEntityManager();
        long [] ids = (long[]) intent;
        selectedPledge = em.find(Pledges.class, new FundingId(ids[0], ids[1]));
        id_text.setText(String.valueOf(selectedPledge.getFunding().getId()));
    }
}
