/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityfund.ui;

import java.awt.event.ItemEvent;
import java.text.DateFormatSymbols;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import universityfund.Utility;
import universityfund.db.DbHelper;
import universityfund.db.models.Donor;
import universityfund.ui.tablemodels.ContactListTableModel;
import universityfund.ui.tablemodels.MembersCategoryTableModel;

/**
 *
 * @author MiriamMarie
 */
public class ReportWindow extends javax.swing.JFrame implements UI {
    Donor selectedDonor;
    Donor selectRep;
    /**
     * Creates new form ReportWindown
     */
    public ReportWindow() {
        initComponents();
        selectedDonor = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        annual_panel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        eachClass_button2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eachCategory_button2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        eachDonor_button2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable(new MembersCategoryTableModel());
        jLabel23 = new javax.swing.JLabel();
        class_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rep_combo = new javax.swing.JComboBox(getReps());
        jScrollPane1 = new javax.swing.JScrollPane();
        contactList_table = new javax.swing.JTable(createTableModel());
        sol_panel = new javax.swing.JPanel();
        solicit_button = new javax.swing.JButton();
        thanks_button = new javax.swing.JButton();
        thank_panel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        name1_text = new javax.swing.JLabel();
        invitation_panel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        form_button = new javax.swing.JButton();
        name2_text = new javax.swing.JLabel();
        set_button = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        name_text = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        monthly_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTS");
        setName("Form"); // NOI18N
        setResizable(false);

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setName("jTabbedPane1"); // NOI18N

        annual_panel2.setBackground(new java.awt.Color(255, 255, 255));
        annual_panel2.setName("annual_panel"); // NOI18N

        jLabel18.setText("Total Amount Raised:");
        jLabel18.setName("jLabel6"); // NOI18N

        eachClass_button2.setText("Proceed>>");
        eachClass_button2.setName("eachClass_button"); // NOI18N
        eachClass_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eachClass_buttonActionPerformed(evt);
            }
        });

        jLabel19.setText("Total for each class:");
        jLabel19.setName("jLabel7"); // NOI18N

        jLabel20.setText("Total for each category:");
        jLabel20.setName("jLabel8"); // NOI18N

        eachCategory_button2.setText("Proceed>>");
        eachCategory_button2.setName("eachCategory_button"); // NOI18N
        eachCategory_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eachCategory_buttonActionPerformed(evt);
            }
        });

        jLabel21.setText("Total for each donor circle:");
        jLabel21.setName("jLabel9"); // NOI18N

        jLabel22.setText("Class total for each donor circle:");
        jLabel22.setName("jLabel10"); // NOI18N

        eachDonor_button2.setText("Proceed>>");
        eachDonor_button2.setName("eachDonor_button"); // NOI18N
        eachDonor_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eachDonor_buttonActionPerformed(evt);
            }
        });

        jButton8.setText("Proceed>>");
        jButton8.setName("jButton6"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane4.setName("jScrollPane2"); // NOI18N

        jTable4.setName("jTable2"); // NOI18N
        jScrollPane4.setViewportView(jTable4);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText(getSum());
        jLabel23.setName("jLabel11"); // NOI18N

        javax.swing.GroupLayout annual_panel2Layout = new javax.swing.GroupLayout(annual_panel2);
        annual_panel2.setLayout(annual_panel2Layout);
        annual_panel2Layout.setHorizontalGroup(
            annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annual_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(annual_panel2Layout.createSequentialGroup()
                        .addGroup(annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(annual_panel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(annual_panel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eachCategory_button2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addGroup(annual_panel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(24, 24, 24)
                                .addComponent(eachClass_button2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addGap(44, 44, 44)
                                .addComponent(eachDonor_button2)))
                        .addGap(0, 254, Short.MAX_VALUE)))
                .addContainerGap())
        );
        annual_panel2Layout.setVerticalGroup(
            annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, annual_panel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(eachClass_button2)
                    .addComponent(jLabel21)
                    .addComponent(eachDonor_button2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(annual_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eachCategory_button2)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jButton8))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Annual Report to Donors", annual_panel2);

        class_panel.setBackground(new java.awt.Color(255, 255, 255));
        class_panel.setName("class_panel"); // NOI18N

        jLabel5.setText("Class Representative:");
        jLabel5.setName("jLabel5"); // NOI18N

        rep_combo.setName("rep_combo"); // NOI18N
        rep_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rep_comboItemStateChanged(evt);
            }
        });
        rep_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep_comboActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        contactList_table.setName("contactList_table"); // NOI18N
        jScrollPane1.setViewportView(contactList_table);

        javax.swing.GroupLayout class_panelLayout = new javax.swing.GroupLayout(class_panel);
        class_panel.setLayout(class_panelLayout);
        class_panelLayout.setHorizontalGroup(
            class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(class_panelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rep_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 408, Short.MAX_VALUE)))
                .addContainerGap())
        );
        class_panelLayout.setVerticalGroup(
            class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rep_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Class Rep Contact List", class_panel);

        sol_panel.setBackground(new java.awt.Color(255, 255, 255));
        sol_panel.setName("sol_panel"); // NOI18N

        solicit_button.setText("Send Solicitation Letter");
        solicit_button.setName("solicit_button"); // NOI18N
        solicit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicit_buttonActionPerformed(evt);
            }
        });

        thanks_button.setText("Send Thanking Letter");
        thanks_button.setName("thanks_button"); // NOI18N
        thanks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanks_buttonActionPerformed(evt);
            }
        });

        thank_panel.setBackground(new java.awt.Color(255, 255, 204));
        thank_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        thank_panel.setName("thank_panel"); // NOI18N

        jLabel24.setText("Dear");
        jLabel24.setName("jLabel12"); // NOI18N

        jScrollPane5.setName("jScrollPane3"); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This letter is to inform you that we have received the promised pledge and gift from you.\n\nThe Beta University would like to send you our deepest gratitudes for choosing to pledge this fiscal year. Hope you would continue pledging pledges to the next pledgable years.\n\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane5.setViewportView(jTextArea1);

        jLabel25.setText("Yours truly,");
        jLabel25.setName("jLabel13"); // NOI18N

        jLabel26.setText("Suzanne Hayes");
        jLabel26.setName("jLabel14"); // NOI18N

        name1_text.setText(" ");
        name1_text.setName("name1_text"); // NOI18N

        javax.swing.GroupLayout thank_panelLayout = new javax.swing.GroupLayout(thank_panel);
        thank_panel.setLayout(thank_panelLayout);
        thank_panelLayout.setHorizontalGroup(
            thank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thank_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thank_panelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name1_text)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thank_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(thank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        thank_panelLayout.setVerticalGroup(
            thank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thank_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(name1_text))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invitation_panel.setBackground(new java.awt.Color(204, 255, 204));
        invitation_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        invitation_panel.setName("invitation_panel"); // NOI18N

        jLabel27.setText("Dear ");
        jLabel27.setName("jLabel15"); // NOI18N

        jScrollPane6.setName("jScrollPane4"); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("This letter is to inform you that you are invited to place a pledge for this fiscal year for you are found to have close-ties with Beta University.\n\nAttached is a form, together with an envelope, for your response letter. The form is for you to fill up certain details about your pledge.\n\nHoping you would consider yourself to be part of the pledging people this pledgable year, and to the next pledgable years to come.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setName("jTextArea2"); // NOI18N
        jScrollPane6.setViewportView(jTextArea2);

        jLabel28.setText("Yours truly,");
        jLabel28.setName("jLabel16"); // NOI18N

        jLabel29.setText("Suzanne Hayes");
        jLabel29.setName("jLabel17"); // NOI18N

        form_button.setText("View Attached Form");
        form_button.setName("form_button"); // NOI18N
        form_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_buttonActionPerformed(evt);
            }
        });

        name2_text.setText(" ");
        name2_text.setName("name2_text"); // NOI18N

        javax.swing.GroupLayout invitation_panelLayout = new javax.swing.GroupLayout(invitation_panel);
        invitation_panel.setLayout(invitation_panelLayout);
        invitation_panelLayout.setHorizontalGroup(
            invitation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invitation_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invitation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addGroup(invitation_panelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name2_text)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invitation_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(invitation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(form_button, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        invitation_panelLayout.setVerticalGroup(
            invitation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invitation_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invitation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(name2_text))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(form_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        set_button.setText("Set...");
        set_button.setName("set_button"); // NOI18N
        set_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_buttonActionPerformed(evt);
            }
        });

        jLabel30.setText("Recipient:");
        jLabel30.setName("jLabel24"); // NOI18N

        name_text.setText(" ");
        name_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        name_text.setName("name_text"); // NOI18N

        jLabel31.setText("Sample Thanking Letter");
        jLabel31.setName("jLabel25"); // NOI18N

        jLabel32.setText("Sample Solicitation Letter");
        jLabel32.setName("jLabel26"); // NOI18N

        javax.swing.GroupLayout sol_panelLayout = new javax.swing.GroupLayout(sol_panel);
        sol_panel.setLayout(sol_panelLayout);
        sol_panelLayout.setHorizontalGroup(
            sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sol_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(set_button)
                    .addComponent(thanks_button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solicit_button)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thank_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(invitation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        sol_panelLayout.setVerticalGroup(
            sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sol_panelLayout.createSequentialGroup()
                .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sol_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thanks_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solicit_button))
                    .addGroup(sol_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(7, 7, 7)
                        .addGroup(sol_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invitation_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(thank_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Solicitation Letters", sol_panel);

        monthly_panel.setBackground(new java.awt.Color(255, 255, 255));
        monthly_panel.setName("monthly_panel"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Month of:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(getMonth()
        );
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total pledges (Received):");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total gifts and donations:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Percentage of pledges:");
        jLabel33.setName("jLabel18"); // NOI18N

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Percentage of gifts and donations:");
        jLabel34.setName("jLabel19"); // NOI18N

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText(getSumGifts());
        jLabel35.setName("jLabel20"); // NOI18N

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(getPercentGifts());
        jLabel36.setName("jLabel21"); // NOI18N

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Total amount raised for this month:");
        jLabel37.setName("jLabel22"); // NOI18N

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText(getSumForThisMonth());
        jLabel38.setName("jLabel23"); // NOI18N

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText(getSumPledges());
        jLabel39.setName("jLabel27"); // NOI18N

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(getPercentPledges());
        jLabel40.setName("jLabel28"); // NOI18N

        javax.swing.GroupLayout monthly_panelLayout = new javax.swing.GroupLayout(monthly_panel);
        monthly_panel.setLayout(monthly_panelLayout);
        monthly_panelLayout.setHorizontalGroup(
            monthly_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        monthly_panelLayout.setVerticalGroup(
            monthly_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthly_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Monthly Report", monthly_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void set_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_buttonActionPerformed
        // TODO add your handling code here:
        new SelectDonorWindow(this).setVisible(true);
    }//GEN-LAST:event_set_buttonActionPerformed

    private void form_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_buttonActionPerformed
        new SampleForm().setVisible(true);
    }//GEN-LAST:event_form_buttonActionPerformed

    private void thanks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanks_buttonActionPerformed
        new MessageSent().setVisible(true);
    }//GEN-LAST:event_thanks_buttonActionPerformed

    private void solicit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicit_buttonActionPerformed
        new MessageSent().setVisible(true);
    }//GEN-LAST:event_solicit_buttonActionPerformed

    private void rep_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rep_comboActionPerformed

    private void rep_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rep_comboItemStateChanged
        // TODO add your handling code here:

        if(evt.getStateChange()==ItemEvent.SELECTED){
            contactList_table.setModel(new ContactListTableModel((Donor)rep_combo.getSelectedItem()));
        }
    }//GEN-LAST:event_rep_comboItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new TotalClassDonorWindow().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void eachDonor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eachDonor_buttonActionPerformed
        new TotalEachDonorCircle().setVisible(true);
    }//GEN-LAST:event_eachDonor_buttonActionPerformed

    private void eachCategory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eachCategory_buttonActionPerformed
        new TotalEachCategoryWindow().setVisible(true);
    }//GEN-LAST:event_eachCategory_buttonActionPerformed

    private void eachClass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eachClass_buttonActionPerformed
        new TotalEachClassWindow().setVisible(true);
    }//GEN-LAST:event_eachClass_buttonActionPerformed

    public Object[] getReps(){
        List <Donor> classReps;
        EntityManager em = DbHelper.getEntityManager();
        classReps = em.createQuery(
                "SELECT d.representative FROM ClassRepresentative d"          
        ).getResultList();
        return classReps.toArray() ;        
    }
    
    public String getMonth(){
        Calendar cal = Calendar.getInstance();
        cal.setTime(Date.from(Instant.now()));
        return getMonthForInt(cal.get(Calendar.MONTH));
    }
    
    public String getMonthForInt(int num) {
        String month = "wrong";
        DateFormatSymbols dfs = new DateFormatSymbols();
        String[] months = dfs.getMonths();
        if (num >= 0 && num <= 11 ) {
            month = months[num];
        }
        return month;
    }
    
    public String getSum(){
        EntityManager em = DbHelper.getEntityManager();
        Object sum = em.createQuery(
           "SELECT SUM(f.completedPayments * (f.amount / f.numberOfPayments)) "
                   + "FROM Funding f WHERE f.dateFunded BETWEEN "
                   + ":begin AND :end"
        ).setParameter("begin", Utility.getBeginDate())
                .setParameter("end", Utility.getEndDate()).getSingleResult();
        if (sum==null)
            return "0";
        else return sum.toString();
    }
    
    public String getSumPledges(){
        EntityManager em = DbHelper.getEntityManager();
        Object[] sum =  (Object[]) em.createNativeQuery(
              "SELECT SUM(AMOUNT), "
                      + "SUM(COMPLETEDPAYMENTS * (AMOUNT / NUMBEROFPAYMENTS)) "
                      + "FROM FUNDING WHERE ID IN ("
                      + "SELECT FUNDINGID FROM PLEDGES) "
                      + "AND YEAR(DATEFUNDED) = ?1 AND MONTH(DATEFUNDED) = ?2"
        ).setParameter(1, java.time.Year.now().getValue()).
                setParameter(2, java.time.MonthDay.now().
                        getMonthValue()).getSingleResult();
        if (sum[0]==null)
            return "0 (0)";
        
        String pledges = sum[0].toString();
        return pledges.concat(" (" + sum[1] + ")");
    }
    
    public String getPercentPledges(){
        String pledges = getSumPledges();
        String all = getSum();
        return String.format("%.2f", ((Float.valueOf(pledges.split("[()]")[1])/
                                        Float.valueOf(all))*100))+"%";
    }

    public String getSumGifts(){
        EntityManager em = DbHelper.getEntityManager();
        Object sum = em.createNativeQuery(
              "SELECT SUM(AMOUNT) " +
                "FROM FUNDING JOIN DONATES ON FUNDINGID = FUNDING.ID "
                      + "JOIN DONOR ON DONORID = DONOR.ID " +
                "WHERE ((YEAR(FUNDING.DATEFUNDED) = ?1 " +
                "AND MONTH(FUNDING.DATEFUNDED) = ?2))"
        ).setParameter(1, java.time.Year.now().getValue()).
                setParameter(2, java.time.MonthDay.now().
                        getMonthValue()).getSingleResult();
        if (sum==null)
            return "0";
        else return sum.toString();
    }
    
    public String getSumForThisMonth(){
        EntityManager em = DbHelper.getEntityManager();
        Object sum = em.createNativeQuery(
              "SELECT SUM(COMPLETEDPAYMENTS * (AMOUNT / NUMBEROFPAYMENTS)) "
                      + "FROM FUNDING WHERE ID IN (SELECT FUNDINGID FROM ("
                      + "SELECT FUNDINGID, DONORID FROM DONATES "
                      + "UNION SELECT FUNDINGID, DONORID FROM PLEDGES"
                      + ") A JOIN DONOR ON DONORID = ID) "
                      + "AND YEAR(DATEFUNDED) = ?1 AND MONTH(DATEFUNDED) = ?2"
        ).setParameter(1, java.time.Year.now().getValue()).
                setParameter(2, java.time.MonthDay.now().
                        getMonthValue()).getSingleResult();
        if (sum==null)
            return "0";
        else return sum.toString();
    }
    
    public String getPercentGifts(){
        String donations = getSumGifts();
        String all = getSum();
        return String.format("%.2f", (Double.valueOf(donations).floatValue()/Double.valueOf(all).floatValue())*100)+"%";
        
    }
    
    private TableModel createTableModel() {
        return new DefaultTableModel();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel annual_panel;
    private javax.swing.JPanel annual_panel1;
    private javax.swing.JPanel annual_panel2;
    private javax.swing.JPanel class_panel;
    private javax.swing.JTable contactList_table;
    private javax.swing.JButton eachCategory_button;
    private javax.swing.JButton eachCategory_button1;
    private javax.swing.JButton eachCategory_button2;
    private javax.swing.JButton eachClass_button;
    private javax.swing.JButton eachClass_button1;
    private javax.swing.JButton eachClass_button2;
    private javax.swing.JButton eachDonor_button;
    private javax.swing.JButton eachDonor_button1;
    private javax.swing.JButton eachDonor_button2;
    private javax.swing.JButton form_button;
    private javax.swing.JPanel invitation_panel;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel monthly_panel;
    private javax.swing.JLabel name1_text;
    private javax.swing.JLabel name2_text;
    private javax.swing.JLabel name_text;
    private javax.swing.JComboBox rep_combo;
    private javax.swing.JButton set_button;
    private javax.swing.JPanel sol_panel;
    private javax.swing.JButton solicit_button;
    private javax.swing.JPanel thank_panel;
    private javax.swing.JButton thanks_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void receiveIntent(Object intent) {
        EntityManager em = DbHelper.getEntityManager();
        selectedDonor = em.find(Donor.class, (long) intent);
        name_text.setText(selectedDonor.getName());
        name1_text.setText(selectedDonor.getName()+",");
        name2_text.setText(selectedDonor.getName()+",");
    }
}
